apiVersion: v1
kind: Secret
metadata:
  name: task-management-secret
  namespace: tasks
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Password123%40"
  POSTGRES_DB: "postgresdb"
  POSTGRES_HOST: "postgres.postgres.svc.cluster.local"
  POSTGRES_PORT: "5432"
