from pydantic import BaseModel, Field, field_serializer, field_validator
from typing import Optional, List
from datetime import datetime
from uuid import UUID
from app.models import TaskStatus, to_utc


# Shared field descriptions so create/update/response tools all read the same way.
_STATUS_DESCRIPTION = (
    "Current workflow status of the task, representing its position in the "
    "workflow lifecycle:\n"
    "- todo: planned but not yet started\n"
    "- inprogress: actively being worked on\n"
    "- blocked: cannot proceed due to dependencies or issues\n"
    "- done: completed successfully\n"
    "- cancelled: cancelled and will not be completed"
)
_CREATOR_DESCRIPTION = "Email address of the person who created the task."
_ASSIGNEE_DESCRIPTION = "Email address of the person assigned to work on this task."
_TARGET_DATE_DESCRIPTION = (
    "Target completion date and time in ISO 8601 format (UTC). Soft deadline."
)
_DESCRIPTION_DESCRIPTION = "Detailed description of what needs to be done."
_COMMENT_DESCRIPTION = "Additional notes, comments, or context about the task."


class TaskCreate(BaseModel):
    """Fields accepted when creating a new task. `id` and timestamps are
    generated by the server and must not be provided."""

    creator: Optional[str] = Field(
        None, max_length=255, description=_CREATOR_DESCRIPTION,
        json_schema_extra={"example": "john.doe@example.com"},
    )
    assignee: Optional[str] = Field(
        None, max_length=255, description=_ASSIGNEE_DESCRIPTION,
        json_schema_extra={"example": "jane.smith@example.com"},
    )
    status: TaskStatus = Field(
        TaskStatus.TODO,
        description=_STATUS_DESCRIPTION + " Defaults to 'todo'.",
    )
    targetDate: Optional[datetime] = Field(
        None, description=_TARGET_DATE_DESCRIPTION,
        json_schema_extra={"example": "2026-06-30T17:00:00Z"},
    )
    description: str = Field(
        ..., min_length=1, max_length=5000, description=_DESCRIPTION_DESCRIPTION,
        json_schema_extra={"example": "Implement new feature X"},
    )
    comment: Optional[str] = Field(
        None, max_length=5000, description=_COMMENT_DESCRIPTION,
        json_schema_extra={"example": "High priority - needed for next release"},
    )

    @field_validator("targetDate")
    @classmethod
    def _normalize_target_date(cls, v: Optional[datetime]) -> Optional[datetime]:
        return to_utc(v) if v is not None else v


class TaskUpdate(BaseModel):
    """Fields accepted when updating a task. All fields are optional; only the
    fields provided are modified. `id`, `creator`, and timestamps are immutable."""

    creator: Optional[str] = Field(None, max_length=255, description=_CREATOR_DESCRIPTION)
    assignee: Optional[str] = Field(None, max_length=255, description=_ASSIGNEE_DESCRIPTION)
    status: Optional[TaskStatus] = Field(None, description=_STATUS_DESCRIPTION)
    targetDate: Optional[datetime] = Field(None, description=_TARGET_DATE_DESCRIPTION)
    description: Optional[str] = Field(
        None, min_length=1, max_length=5000, description=_DESCRIPTION_DESCRIPTION
    )
    comment: Optional[str] = Field(None, max_length=5000, description=_COMMENT_DESCRIPTION)

    @field_validator("targetDate")
    @classmethod
    def _normalize_target_date(cls, v: Optional[datetime]) -> Optional[datetime]:
        return to_utc(v) if v is not None else v


class TaskResponse(BaseModel):
    """Complete task object with all fields including server-generated metadata."""

    id: UUID = Field(..., description="Unique identifier (UUID v4) for the task. Immutable.")
    creator: Optional[str] = Field(None, description=_CREATOR_DESCRIPTION)
    assignee: Optional[str] = Field(None, description=_ASSIGNEE_DESCRIPTION)
    status: TaskStatus = Field(..., description=_STATUS_DESCRIPTION)
    targetDate: Optional[datetime] = Field(None, description=_TARGET_DATE_DESCRIPTION)
    description: str = Field(..., description=_DESCRIPTION_DESCRIPTION)
    comment: Optional[str] = Field(None, description=_COMMENT_DESCRIPTION)
    createdAt: datetime = Field(
        ..., alias="createdAt",
        description="Timestamp (ISO 8601, UTC) when the task was created. Immutable.",
    )
    updatedAt: datetime = Field(
        ..., alias="updatedAt",
        description="Timestamp (ISO 8601, UTC) when the task was last updated.",
    )

    @field_serializer("createdAt", "updatedAt")
    def _serialize_required_datetime(self, value: datetime) -> datetime:
        """Emit required timestamps as timezone-aware UTC (RFC 3339 with offset),
        regardless of whether the backend preserved tzinfo."""
        return to_utc(value)

    @field_serializer("targetDate")
    def _serialize_optional_datetime(self, value: Optional[datetime]) -> Optional[datetime]:
        """Emit the optional targetDate as timezone-aware UTC when present."""
        return to_utc(value) if value is not None else value

    class Config:
        from_attributes = True
        populate_by_name = True


class TaskListResponse(BaseModel):
    """Container object wrapping the list of tasks returned by the list endpoint."""

    tasks: List[TaskResponse] = Field(
        ..., description="The list of tasks matching the query."
    )


class ErrorResponse(BaseModel):
    """Standard error response returned for all error scenarios."""

    errorId: UUID = Field(
        ...,
        description="Unique identifier for this specific error occurrence.",
    )
    timestamp: datetime = Field(
        ...,
        description="Timestamp (ISO 8601, UTC) when the error occurred.",
    )
    code: str = Field(
        ...,
        description=(
            "Machine-readable error code. Common values: VALIDATION_ERROR, "
            "NOT_FOUND, INVALID_UUID, INVALID_PARAMETER, INTERNAL_ERROR."
        ),
    )
    message: str = Field(..., description="Human-readable description of what went wrong.")

    @field_serializer("timestamp")
    def _serialize_timestamp(self, value: datetime) -> datetime:
        return to_utc(value) if value is not None else value
